### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/container-runtime#1]
* The zsh profile includes docker-zsh-completion but not zsh:
package: 2:docker-zsh-completion-1.13.1-13.git51eb16e.module_9e7f2f96.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     zsh

* Same problem with the vim profile.

* Docker-fish-completion requires fish.

* Docker-unit-test requires yajl.

* Docker-rhsubscription requires subscription-manager-plugin-container

* Docker needs lvm2 and python-rhsm-certificates

**Comment by TomasTomecek** [comment]
pretty good point with the profiles, could be worth commenting them out and filtering the packages.

Isn't lvm2 part of base-runtime?

**Comment by r4f4** [comment]
Right now it's filtered out from it but we can include it and some of its deps back.

**Comment by TomasTomecek** [comment]
http://pkgs.fedoraproject.org/cgit/modules/container-runtime.git/commit/?h=f26&id=0c595b43a9f822a756bdda08d3a0a695b7606b9f
http://pkgs.fedoraproject.org/cgit/modules/container-runtime.git/commit/?h=f26&id=f82855484a0e76d87396d562aa7635e4ae5100be
http://pkgs.fedoraproject.org/cgit/modules/container-runtime.git/commit/?h=f26&id=55b2c3d86073e956fcff8054a51eaa11c5b55472
http://pkgs.fedoraproject.org/cgit/modules/container-runtime.git/commit/?h=f26&id=b11daf4756233de1be081e07e3297ada1902df1f

should address most of the issues: lvm2 issue is pending, and we need a new build of s-u which will include python-rhsm-certificates

**Comment by r4f4** [comment]
Thank you for the fixes. I guess docker-fish-completion could be filtered out?

**Comment by TomasTomecek** [comment]
oh! I missed it, thanks for the pointer:

http://pkgs.fedoraproject.org/cgit/modules/container-runtime.git/commit/?h=f26&id=f2f3c715cd05006d54a99da1170a2e844a425806

build in progress

**Comment by TomasTomecek** [comment]
build failed on wait repo -_-

**Comment by TomasTomecek** [comment]
```
ttomecek's build #658 of container-runtime-f26 is in the "ready" state (koji tag: "module-46947e74d50e5589")
```

shall we close?

**Comment by r4f4** [comment]
Thank you for the fix.
